name: findme
publish_to: 'none'
version: 0.0.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sawo: ^0.1.2
  get: ^4.3.8
  flutter_map: ^0.14.0
  latlong2: ^0.8.0
  flutter_svg: ^0.22.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
